version: '3'
services:
  apache:
    build: .
    image: httpd
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html
    networks:
      - default
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./data/dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - ./data/persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - default
