version: '3'
services:
  apache:
    build: .
    image: httpd
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html
    networks:
      - default
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=database
    volumes:
      - ./data/dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - ./data/persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8000:80
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

volumes:
  persistent:
